<!DOCTYPE html>
<html lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title>页面未找到-多彩饰家</title>
    <!-- content="180，即180秒后返回主页，可根据需要修改或者删除这段代码 -->
    <meta http-equiv="refresh" content="180;url=http://duocai.cn/m">
    <style>
        body, div {
            margin: 0;
            padding: 0;
        }

        body {
            background: url("/img/common/404_error_bg.jpg") repeat-x scroll 0 0 #67ACE4;
        }

        #container {
            margin: 0 auto;
            padding-top: 50px;
            text-align: center;
            width: 560px;
        }

        #container img {
            border: medium none;
            margin-bottom: 50px;
        }

        #container .error {
            height: 200px;
            position: relative;
        }

        #container .error img {
            bottom: -50px;
            position: absolute;
            right: -50px;
        }

        #container .msg {
            margin-bottom: 65px;
        }

        #cloud {
            background: url("/img/common/404_error_cloud.png") repeat-x scroll 0 0 transparent;
            bottom: 0;
            height: 170px;
            position: absolute;
            width: 100%;
        }
    </style>
</head>
<body>
<div id="container"><img class="png" src="/img/common/404.png"/>
    <img class="png msg" src="/img/common/404_msg.png"/>
    <p>
        <a href="http://duocai.cn/m/">
            <img class="png" src="/img/common/404_to_index.png"/>
        </a>
    </p>
</div>
<div id="cloud" class="png"></div>
</body>
</html>